In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\python310\lib\site-packages (2.0.29)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\python310\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\python310\lib\site-packages (from sqlalchemy) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
#COnnection
connection_string = "mssql+pyodbc://moeness:azerty@localhost/DW_hr?driver=ODBC+Driver+17+for+SQL+Server"

In [3]:
# Create SQLAlchemy engine
engine = create_engine(connection_string)

In [4]:
# Create a connection
conn = engine.connect()

In [5]:
# Execute SQL query and fetch data into a pandas DataFrame
query = text('SELECT * FROM [dbo].[Fact_trainings]')
result = conn.execute(query)
fact_trainings = pd.DataFrame(result.fetchall(), columns=result.keys())

In [6]:
conn.close()

In [7]:
print(fact_trainings.head())

                           FK_Employees FK_Projecct  Fk_Training  \
0  fd98e2a4-0ec7-4558-b660-cb6961104638        None            1
1  ee42342c-3720-492c-b72a-d1a83f51cceb        None            2
2  f10df5eb-3556-4b33-b3da-42f0490d380b        None            3
3  e7a22d72-ae70-4dd7-b424-e20d731b79de        None            4
4  ef8dfaff-efb8-4d49-b02e-ca57993d2888        None            5

  Price_of_trainning Duration
0               None     None
1               None     None
2               None     None
3               None     None
4               None     None

In [8]:
fact_trainings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4518 entries, 0 to 4517
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FK_Employees        3488 non-null   object
 1   FK_Projecct         0 non-null      object
 2   Fk_Training         4518 non-null   int64
 3   Price_of_trainning  994 non-null    object
 4   Duration            994 non-null    object
dtypes: int64(1), object(4)
memory usage: 176.6+ KB

In [9]:
fact_trainings.drop(['FK_Projecct'], axis=1, inplace=True)

In [10]:
fact_trainings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4518 entries, 0 to 4517
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FK_Employees        3488 non-null   object
 1   Fk_Training         4518 non-null   int64
 2   Price_of_trainning  994 non-null    object
 3   Duration            994 non-null    object
dtypes: int64(1), object(3)
memory usage: 141.3+ KB

In [11]:
import pandas as pd

In [38]:
# Convertir FK_Employees en int64
fact_trainings['FK_Employees'] = pd.to_numeric(fact_trainings['FK_Employees'], errors='coerce')

In [40]:
# Supprimer les éventuelles valeurs NaN après la conversion
fact_trainings = fact_trainings.dropna(subset=['FK_Employees'])

In [65]:
# Conversion de FK_Employees en int pour correspondre à Employee_PK
fact_trainings['FK_Employees'] = fact_trainings['FK_Employees'].astype('int64')

In [66]:
fact_trainings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FK_Employees        0 non-null      int64
 1   Fk_Training         0 non-null      int64
 2   Price_of_trainning  0 non-null      object
 3   Duration            0 non-null      object
dtypes: int64(2), object(2)
memory usage: 0.0+ bytes

In [12]:
# Create a connection
conn = engine.connect()

In [13]:
query = text('SELECT * FROM [dbo].[dim_employees]')
result = conn.execute(query)
dim_employees = pd.DataFrame(result.fetchall(), columns=result.keys())

In [14]:
conn.close()

In [15]:
dim_employees

,Employee_PK,CODE,NAME_EMP,GENDER,ADDRESS,MARITAL_STATUS,GRAD_UNIVERSITY,TYPE_DIPLOMA,EMAIL,LANGUAGE,...,TYPE_CONTRACT,TECHNOLOGIES,CONTRACT_START,CONTRACT_END,ACTIVITY,TENURE,ADRESSE_MISSION,LAST_LEAVE_TYPE,SOURCE_of_employment,Grade
0,1,e1856ea4-19a0-4c60-af39-689dced5e0e1,Tony Freeman,F,"1087 Blake Spring\nLindsayland, GU 63148",0,None,Master,tony_freeman@example.com,"Arabe, Others",...,CDD,None,2018-02-28,1753-01-01,None,1,None,Mission,Free Application,RH
1,2,80705c76-cbaf-4010-974d-6dde90fe1a69,Donna Larson,F,"86475 White Ports Suite 192\nMooreton, WV 86516",0,None,Licence,donna_larson@example.com,Anglais,...,CIVP,None,2019-06-02,2022-12-07,None,1,None,Sans_Solde,Recommendation,RH
2,3,90438efd-4d75-4c03-9f23-0821adcaf41b,Lauren Santos,M,"9702 Wilson Falls Suite 470\nDennisfort, VT 52820",1,None,Licence,lauren_santos@example.com,"Arabe, Anglais, Others",...,CDI,None,2014-03-03,2022-03-05,None,1,None,Mission,Recommendation,Financier
3,4,5aeecf88-0749-46f0-b7f5-4801c6a8a143,David Kennedy,M,Unit 6731 Box 3814\nDPO AA 82476,0,None,Licence,david_kennedy@example.com,"Anglais, Others, Arabe",...,CDI,None,2011-10-28,2023-09-27,None,1,None,Sans_Solde,Free Application,Financier
4,5,5d9df20f-b4c0-473c-8805-4503b34ad728,Casey Turner,M,"56039 Steven Springs Apt. 717\nMarkmouth, ID 9...",0,None,Licence,casey_turner@example.com,"Anglais, Arabe, Francais",...,CDD,None,2017-09-21,1753-01-01,None,0,None,Sans_Solde,Recommendation,Chef Service
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2735,2736,ffb72fc7-6a78-4152-8437-927de590e0de,Robert Chambers,M,"03705 Barrett Radial Suite 613\nLake Lisa, UT ...",1,Nelson Ltd,Doctoral,douglas81@example.org,"anglais, others, francais, arabe",...,CDD,"Software Engineering, Telecom",2022-04-08,2024-08-23,Technical,1,None,sans_solde,ex-vacataire,Medical secretary
2736,2737,ffc3544d-26ee-45a4-8632-3a7006d2535a,Adrian Stevens,F,"2344 Marcus Turnpike Apt. 464\nNorth Emily, MP...",0,Graham PLC,Doctoral,hpearson@example.net,"francais, others, arabe",...,CDD,"Telecom, Software Engineering",2013-05-03,2016-06-02,Mission,1,"0379 Perkins Junction\nWest Marvinview, MI 01016",mission,recruitment_session,Risk analyst
2737,2738,ffc417c6-8532-4f0a-b711-b5dc2352594e,Taylor Taylor,F,"614 Guzman Wells\nWest Angelamouth, MI 94939",1,Washington LLC,Doctoral,ievans@example.com,"francais, arabe, anglais, others",...,CDI,"Telecom, Software Engineering",2018-06-16,2020-07-17,Mission,0,"05526 Brittany Pines Apt. 260\nEast Sara, AR 7...",ordinary,recruitment_session,Geographical information systems officer
2738,2739,ffd5eb73-bb42-4fca-83e2-31e5472a5e4e,Katherine Nelson,M,"19653 Kelsey Plains\nLake Andrewbury, WY 20017",0,"Mckay, Page and Mcpherson",Master,mgomez@example.com,"others, anglais, arabe",...,CDI,Telecom,2021-05-03,1753-01-01,Technical,0,None,sick,free_application,"Lecturer, further education"
2739,2740,ff799cd7-9b5b-40c2-85b2-c80b2546b892,Craig Miller,F,"627 Carter Glen Suite 465\nWest Chad, UT 64381",0,"Dunn, Green and Franco",Master,ngross@example.org,"arabe, francais",...,CIVP,Telecom,2007-01-24,2020-01-06,Mission,1,"65471 Munoz Union Suite 305\nWest Sandramouth,...",ordinary,recruitment_session,Dietitian

In [16]:
dim_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2740 entries, 0 to 2739
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Employee_PK           2740 non-null   int64
 1   CODE                  2740 non-null   object
 2   NAME_EMP              2737 non-null   object
 3   GENDER                2740 non-null   object
 4   ADDRESS               2733 non-null   object
 5   MARITAL_STATUS        2740 non-null   int64
 6   GRAD_UNIVERSITY       1457 non-null   object
 7   TYPE_DIPLOMA          2740 non-null   object
 8   EMAIL                 2736 non-null   object
 9   LANGUAGE              2737 non-null   object
 10  POSITION              2740 non-null   object
 11  STARTING_DATE         2740 non-null   object
 12  TYPE_CONTRACT         2738 non-null   object
 13  TECHNOLOGIES          1456 non-null   object
 14  CONTRACT_START        2740 non-null   object
 15  CONTRACT_END          2740 non-null   object
 16  ACTIVITY              1459 non-null   object
 17  TENURE                2740 non-null   int64
 18  ADRESSE_MISSION       517 non-null    object
 19  LAST_LEAVE_TYPE       2740 non-null   object
 20  SOURCE_of_employment  2740 non-null   object
 21  Grade                 2739 non-null   object
dtypes: int64(3), object(19)
memory usage: 471.1+ KB

In [17]:
# Create a connection
conn = engine.connect()

In [18]:
query = text('SELECT * FROM [dbo].[dim_trainings]')
result = conn.execute(query)
dim_trainings = pd.DataFrame(result.fetchall(), columns=result.keys())

In [19]:
conn.close()

In [20]:
dim_trainings

,course_id,course_Name,Organization,Duration,Price,Difficulty_Level,Course_Rating,src
0,1,Write A Feature Length Screenplay For Film Or ...,Michigan State University,None,None,Beginner,4.8,coursera_training
1,2,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,None,None,Beginner,4.8,coursera_training
2,3,Silicon Thin Film Solar Cells,ecole Polytechnique,None,None,Advanced,4.1,coursera_training
3,4,Finance for Managers,IESE Business School,None,None,Intermediate,4.8,coursera_training
4,5,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,None,None,Beginner,4.6,coursera_training
...,...,...,...,...,...,...,...,...
4513,4531,Docker from A to Z™: Swarm + Jenkins,"James Kayes-Smith, Samy Mkacher",9,199.99,Intermediate,None,Udemy_scraping
4514,4532,"Docker, From Zero To Hero: Become a DevOps Doc...",Ricardo Andre Gonzalez Gomez,10,229.99,All Levels,None,Udemy_scraping
4515,4533,Microsoft SQL Server Development for Everyone,"Trevoir Williams, Learn IT University, Andrii ...",14,269.99,All Levels,None,Udemy_scraping
4516,4534,Complete ASP.NET Core and Entity Framework Dev...,Trevoir Williams,14.5,269.99,All Levels,None,Udemy_scraping
4517,4535,The Complete NFT Web Development Course - Zero...,"Clarian North, Media Training Worldwide Digital",24,319.99,All Levels,None,Udemy_scraping

In [21]:
dim_trainings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4518 entries, 0 to 4517
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   course_id         4518 non-null   int64
 1   course_Name       4502 non-null   object
 2   Organization      4502 non-null   object
 3   Duration          994 non-null    object
 4   Price             994 non-null    object
 5   Difficulty_Level  4502 non-null   object
 6   Course_Rating     3508 non-null   object
 7   src               4518 non-null   object
dtypes: int64(1), object(7)
memory usage: 282.5+ KB

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [53]:
# Fusion des données
data = pd.merge(fact_trainings, dim_employees, left_on='FK_Employees', right_on='CODE', how='left')
data = pd.merge(data, dim_trainings, left_on='Fk_Training', right_on='course_id', how='left')

In [50]:
data

,FK_Employees,Fk_Training,Price_of_trainning,Duration_x,Employee_PK,CODE,NAME_EMP,GENDER,ADDRESS,MARITAL_STATUS,...,SOURCE_of_employment,Grade,course_id,course_Name,Organization,Duration_y,Price,Difficulty_Level,Course_Rating,src
0,776,1,10,163,2727.000000,776,183,1,604,0.000000,...,3,36,1,4358,392,163,10,2,27,2
1,682,2,10,163,2628.000000,682,579,0,321,0.000000,...,2,397,2,634,144,163,10,2,27,2
2,704,3,10,163,2651.000000,704,124,1,139,0.000000,...,3,240,3,3607,690,163,10,0,20,2
3,640,4,10,163,2584.000000,640,73,1,663,1.000000,...,3,341,4,1546,267,163,10,5,27,2
4,695,5,10,163,2641.000000,695,145,1,97,1.000000,...,1,379,5,3455,144,163,10,2,25,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4513,265,4531,3,157,2469.227924,265,754,2,788,0.449828,...,0,431,4531,1322,291,157,3,5,31,0
4514,265,4532,4,2,2469.227924,265,754,2,788,0.449828,...,0,431,4532,1323,491,2,4,1,31,0
4515,265,4533,5,14,2469.227924,265,754,2,788,0.449828,...,0,431,4533,2822,606,14,5,1,31,0
4516,265,4534,5,15,2469.227924,265,754,2,788,0.449828,...,0,431,4534,828,605,15,5,1,31,0
4517,265,4535,6,39,2469.227924,265,754,2,788,0.449828,...,0,431,4535,3957,122,39,6,1,31,0

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4518 entries, 0 to 4517
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FK_Employees          4518 non-null   int32
 1   Fk_Training           4518 non-null   int64
 2   Price_of_trainning    4518 non-null   int32
 3   Duration_x            4518 non-null   int32
 4   Employee_PK           4518 non-null   float64
 5   CODE                  4518 non-null   int32
 6   NAME_EMP              4518 non-null   int32
 7   GENDER                4518 non-null   int32
 8   ADDRESS               4518 non-null   int32
 9   MARITAL_STATUS        4518 non-null   float64
 10  GRAD_UNIVERSITY       4518 non-null   int32
 11  TYPE_DIPLOMA          4518 non-null   int32
 12  EMAIL                 4518 non-null   int32
 13  LANGUAGE              4518 non-null   int32
 14  POSITION              4518 non-null   int32
 15  STARTING_DATE         4518 non-null   object
 16  TYPE_CONTRACT         4518 non-null   object
 17  TECHNOLOGIES          4518 non-null   object
 18  CONTRACT_START        4518 non-null   object
 19  CONTRACT_END          4518 non-null   object
 20  ACTIVITY              4518 non-null   object
 21  TENURE                4518 non-null   float64
 22  ADRESSE_MISSION       4518 non-null   object
 23  LAST_LEAVE_TYPE       4518 non-null   object
 24  SOURCE_of_employment  4518 non-null   object
 25  Grade                 4518 non-null   object
 26  course_id             4518 non-null   int64
 27  course_Name           4518 non-null   object
 28  Organization          4518 non-null   object
 29  Duration_y            4518 non-null   object
 30  Price                 4518 non-null   object
 31  Difficulty_Level      4518 non-null   object
 32  Course_Rating         4518 non-null   object
 33  src                   4518 non-null   object
dtypes: float64(3), int32(12), int64(2), object(17)
memory usage: 1023.6+ KB

In [26]:
# Gestion des valeurs manquantes
data.fillna(data.mean(), inplace=True)  # Imputation pour les variables numériques
data.fillna('Unknown', inplace=True)  # Imputation pour les variables catégorielles

C:\Users\MOEµNESS\AppData\Local\Temp\ipykernel_18880\1070802196.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.fillna(data.mean(), inplace=True)  # Imputation pour les variables numériques

In [29]:
date_cols = ['STARTING_DATE', 'CONTRACT_START', 'CONTRACT_END']

# Convert date columns to strings
for col in date_cols:
    data[col] = data[col].astype(str)

In [42]:
# Encode categorical variables
label_encoders = {}
for col in X.select_dtypes(include=['object']).columns:
    label_encoders[col] = LabelEncoder()
    X[col] = label_encoders[col].fit_transform(X[col])

In [43]:
# Séparation des caractéristiques et de la cible
X = data.drop(['Fk_Training', 'course_Name', 'Organization', 'src'], axis=1)
y = data['Fk_Training']  # Ou 'course_Name'

In [56]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4518 entries, 0 to 4517
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FK_Employees          4518 non-null   int32
 1   Price_of_trainning    4518 non-null   int32
 2   Duration_x            4518 non-null   int32
 3   Employee_PK           4518 non-null   float64
 4   CODE                  4518 non-null   int32
 5   NAME_EMP              4518 non-null   int32
 6   GENDER                4518 non-null   int32
 7   ADDRESS               4518 non-null   int32
 8   MARITAL_STATUS        4518 non-null   float64
 9   GRAD_UNIVERSITY       4518 non-null   int32
 10  TYPE_DIPLOMA          4518 non-null   int32
 11  EMAIL                 4518 non-null   int32
 12  LANGUAGE              4518 non-null   int32
 13  POSITION              4518 non-null   int32
 14  STARTING_DATE         4518 non-null   int32
 15  TYPE_CONTRACT         4518 non-null   int32
 16  TECHNOLOGIES          4518 non-null   int32
 17  CONTRACT_START        4518 non-null   int32
 18  CONTRACT_END          4518 non-null   int32
 19  ACTIVITY              4518 non-null   int32
 20  TENURE                4518 non-null   float64
 21  ADRESSE_MISSION       4518 non-null   int32
 22  LAST_LEAVE_TYPE       4518 non-null   int32
 23  SOURCE_of_employment  4518 non-null   int32
 24  Grade                 4518 non-null   int32
 25  course_id             4518 non-null   int64
 26  Duration_y            4518 non-null   int32
 27  Price                 4518 non-null   int32
 28  Difficulty_Level      4518 non-null   int32
 29  Course_Rating         4518 non-null   int32
dtypes: float64(3), int32(26), int64(1)
memory usage: 635.3 KB

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4518 entries, 0 to 4517
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FK_Employees          4518 non-null   int32
 1   Fk_Training           4518 non-null   int64
 2   Price_of_trainning    4518 non-null   int32
 3   Duration_x            4518 non-null   int32
 4   Employee_PK           4518 non-null   float64
 5   CODE                  4518 non-null   int32
 6   NAME_EMP              4518 non-null   int32
 7   GENDER                4518 non-null   int32
 8   ADDRESS               4518 non-null   int32
 9   MARITAL_STATUS        4518 non-null   float64
 10  GRAD_UNIVERSITY       4518 non-null   int32
 11  TYPE_DIPLOMA          4518 non-null   int32
 12  EMAIL                 4518 non-null   int32
 13  LANGUAGE              4518 non-null   int32
 14  POSITION              4518 non-null   int32
 15  STARTING_DATE         4518 non-null   int32
 16  TYPE_CONTRACT         4518 non-null   int32
 17  TECHNOLOGIES          4518 non-null   int32
 18  CONTRACT_START        4518 non-null   int32
 19  CONTRACT_END          4518 non-null   int32
 20  ACTIVITY              4518 non-null   int32
 21  TENURE                4518 non-null   float64
 22  ADRESSE_MISSION       4518 non-null   int32
 23  LAST_LEAVE_TYPE       4518 non-null   int32
 24  SOURCE_of_employment  4518 non-null   int32
 25  Grade                 4518 non-null   int32
 26  course_id             4518 non-null   int64
 27  course_Name           4518 non-null   int32
 28  Organization          4518 non-null   int32
 29  Duration_y            4518 non-null   int32
 30  Price                 4518 non-null   int32
 31  Difficulty_Level      4518 non-null   int32
 32  Course_Rating         4518 non-null   int32
 33  src                   4518 non-null   int32
dtypes: float64(3), int32(29), int64(2)
memory usage: 723.6 KB

In [45]:
# Division en ensembles de test et d'apprentissage
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [47]:
# Création et entraînement du modèle KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [48]:
# Make predictions
y_pred = knn.predict(X_test_scaled)

In [57]:
# Prédiction et évaluation
predictions = knn.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           9       0.00      0.00      0.00       1.0
          15       0.00      0.00      0.00       1.0
          18       0.00      0.00      0.00       1.0
          20       0.00      0.00      0.00       1.0
          24       0.00      0.00      0.00       1.0
          27       0.00      0.00      0.00       1.0
          30       0.00      0.00      0.00       1.0
          33       0.00      0.00      0.00       1.0
          34       0.00      0.00      0.00       1.0
          44       0.00      0.00      0.00       1.0
          46       0.00      0.00      0.00       1.0
          52       0.00      0.00      0.00       1.0
          62       0.00      0.00      0.00       1.0
          70       0.00      0.00      0.00       1.0
          71       0.00      0.00      0.00       1.0
          74       0.00      0.00      0.00       1.0
          81       0.00      0.00      0.00       1.0
          85       0.00      0.00      0.00       1.0
          94       0.00      0.00      0.00       1.0
          96       0.00      0.00      0.00       1.0
          97       0.00      0.00      0.00       1.0
         110       0.00      0.00      0.00       1.0
         114       0.00      0.00      0.00       1.0
         121       0.00      0.00      0.00       1.0
         123       0.00      0.00      0.00       1.0
         133       0.00      0.00      0.00       1.0
         135       0.00      0.00      0.00       1.0
         140       0.00      0.00      0.00       1.0
         146       0.00      0.00      0.00       1.0
         151       0.00      0.00      0.00       1.0
         152       0.00      0.00      0.00       1.0
         153       0.00      0.00      0.00       1.0
         154       0.00      0.00      0.00       1.0
         159       0.00      0.00      0.00       1.0
         168       0.00      0.00      0.00       1.0
         170       0.00      0.00      0.00       1.0
         172       0.00      0.00      0.00       1.0
         177       0.00      0.00      0.00       1.0
         179       0.00      0.00      0.00       1.0
         181       0.00      0.00      0.00       1.0
         182       0.00      0.00      0.00       1.0
         187       0.00      0.00      0.00       1.0
         191       0.00      0.00      0.00       1.0
         194       0.00      0.00      0.00       1.0
         195       0.00      0.00      0.00       1.0
         199       0.00      0.00      0.00       1.0
         202       0.00      0.00      0.00       1.0
         206       0.00      0.00      0.00       1.0
         208       0.00      0.00      0.00       1.0
         214       0.00      0.00      0.00       1.0
         217       0.00      0.00      0.00       1.0
         223       0.00      0.00      0.00       1.0
         230       0.00      0.00      0.00       1.0
         232       0.00      0.00      0.00       1.0
         241       0.00      0.00      0.00       1.0
         242       0.00      0.00      0.00       1.0
         243       0.00      0.00      0.00       1.0
         254       0.00      0.00      0.00       1.0
         255       0.00      0.00      0.00       1.0
         257       0.00      0.00      0.00       1.0
         273       0.00      0.00      0.00       1.0
         277       0.00      0.00      0.00       1.0
         282       0.00      0.00      0.00       1.0
         290       0.00      0.00      0.00       1.0
         292       0.00      0.00      0.00       1.0
         293       0.00      0.00      0.00       1.0
         294       0.00      0.00      0.00       1.0
         299       0.00      0.00      0.00       1.0
         300       0.00      0.00      0.00       1.0
         301       0.00      0.00      0.00       1.0
         308       0.00      0.00      0.00       1.0
         311       0.00      0.00      0.00       1.0
         312       0.00      0.00      0.00       1.0
         317       0.00      0.00      0.00       1.0
         318       0.00      0.00      0.00       1.0
         321       0.00      0.00      0.00       1.0
         325       0.00      0.00      0.00       1.0
         333       0.00      0.00      0.00       1.0
         335       0.00      0.00      0.00       1.0
         353       0.00      0.00      0.00       1.0
         354       0.00      0.00      0.00       1.0
         359       0.00      0.00      0.00       1.0
         363       0.00      0.00      0.00       1.0
         369       0.00      0.00      0.00       1.0
         370       0.00      0.00      0.00       1.0
         374       0.00      0.00      0.00       1.0
         379       0.00      0.00      0.00       1.0
         390       0.00      0.00      0.00       1.0
         396       0.00      0.00      0.00       1.0
         405       0.00      0.00      0.00       1.0
         411       0.00      0.00      0.00       1.0
         413       0.00      0.00      0.00       1.0
         417       0.00      0.00      0.00       1.0
         418       0.00      0.00      0.00       1.0
         419       0.00      0.00      0.00       1.0
         429       0.00      0.00      0.00       1.0
         432       0.00      0.00      0.00       1.0
         435       0.00      0.00      0.00       1.0
         436       0.00      0.00      0.00       1.0
         441       0.00      0.00      0.00       1.0
         446       0.00      0.00      0.00       1.0
         448       0.00      0.00      0.00       1.0
         453       0.00      0.00      0.00       1.0
         455       0.00      0.00      0.00       1.0
         460       0.00      0.00      0.00       1.0
         464       0.00      0.00      0.00       1.0
         466       0.00      0.00      0.00       1.0
         468       0.00      0.00      0.00       1.0
         471       0.00      0.00      0.00       1.0
         474       0.00      0.00      0.00       1.0
         481       0.00      0.00      0.00       1.0
         489       0.00      0.00      0.00       1.0
         493       0.00      0.00      0.00       1.0
         497       0.00      0.00      0.00       1.0
         500       0.00      0.00      0.00       1.0
         508       0.00      0.00      0.00       1.0
         509       0.00      0.00      0.00       1.0
         514       0.00      0.00      0.00       1.0
         517       0.00      0.00      0.00       0.0
         521       0.00      0.00      0.00       1.0
         533       0.00      0.00      0.00       1.0
         537       0.00      0.00      0.00       1.0
         541       0.00      0.00      0.00       1.0
         547       0.00      0.00      0.00       1.0
         554       0.00      0.00      0.00       1.0
         558       0.00      0.00      0.00       1.0
         564       0.00      0.00      0.00       1.0
         567       0.00      0.00      0.00       1.0
         571       0.00      0.00      0.00       1.0
         587       0.00      0.00      0.00       1.0
         592       0.00      0.00      0.00       1.0
         597       0.00      0.00      0.00       1.0
         599       0.00      0.00      0.00       1.0
         601       0.00      0.00      0.00       1.0
         602       0.00      0.00      0.00       1.0
         605       0.00      0.00      0.00       1.0
         624       0.00      0.00      0.00       1.0
         628       0.00      0.00      0.00       1.0
         629       0.00      0.00      0.00       1.0
         646       0.00      0.00      0.00       1.0
         647       0.00      0.00      0.00       1.0
         659       0.00      0.00      0.00       1.0
         672       0.00      0.00      0.00       1.0
         674       0.00      0.00      0.00       1.0
         680       0.00      0.00      0.00       1.0
         681       0.00      0.00      0.00       1.0
         684       0.00      0.00      0.00       1.0
         687       0.00      0.00      0.00       1.0
         695       0.00      0.00      0.00       1.0
         697       0.00      0.00      0.00       1.0
         709       0.00      0.00      0.00       1.0
         722       0.00      0.00      0.00       1.0
         724       0.00      0.00      0.00       1.0
         725       0.00      0.00      0.00       1.0
         730       0.00      0.00      0.00       0.0
         735       0.00      0.00      0.00       1.0
         737       0.00      0.00      0.00       1.0
         738       0.00      0.00      0.00       1.0
         749       0.00      0.00      0.00       1.0
         751       0.00      0.00      0.00       1.0
         756       0.00      0.00      0.00       1.0
         760       0.00      0.00      0.00       1.0
         764       0.00      0.00      0.00       1.0
         769       0.00      0.00      0.00       1.0
         781       0.00      0.00      0.00       1.0
         788       0.00      0.00      0.00       1.0
         792       0.00      0.00      0.00       1.0
         794       0.00      0.00      0.00       1.0
         795       0.00      0.00      0.00       1.0
         799       0.00      0.00      0.00       1.0
         803       0.00      0.00      0.00       1.0
         805       0.00      0.00      0.00       1.0
         807       0.00      0.00      0.00       1.0
         810       0.00      0.00      0.00       1.0
         812       0.00      0.00      0.00       1.0
         815       0.00      0.00      0.00       1.0
         816       0.00      0.00      0.00       1.0
         817       0.00      0.00      0.00       1.0
         834       0.00      0.00      0.00       1.0
         838       0.00      0.00      0.00       1.0
         843       0.00      0.00      0.00       1.0
         847       0.00      0.00      0.00       1.0
         848       0.00      0.00      0.00       1.0
         861       0.00      0.00      0.00       1.0
         862       0.00      0.00      0.00       1.0
         867       0.00      0.00      0.00       1.0
         874       0.00      0.00      0.00       1.0
         876       0.00      0.00      0.00       1.0
         882       0.00      0.00      0.00       1.0
         884       0.00      0.00      0.00       1.0
         886       0.00      0.00      0.00       1.0
         894       0.00      0.00      0.00       1.0
         898       0.00      0.00      0.00       1.0
         901       0.00      0.00      0.00       1.0
         912       0.00      0.00      0.00       1.0
         916       0.00      0.00      0.00       1.0
         920       0.00      0.00      0.00       1.0
         942       0.00      0.00      0.00       1.0
         949       0.00      0.00      0.00       1.0
         950       0.00      0.00      0.00       1.0
         965       0.00      0.00      0.00       1.0
         969       0.00      0.00      0.00       1.0
         974       0.00      0.00      0.00       1.0
         982       0.00      0.00      0.00       1.0
         983       0.00      0.00      0.00       1.0
         999       0.00      0.00      0.00       1.0
        1001       0.00      0.00      0.00       1.0
        1004       0.00      0.00      0.00       1.0
        1006       0.00      0.00      0.00       1.0
        1015       0.00      0.00      0.00       1.0
        1023       0.00      0.00      0.00       1.0
        1029       0.00      0.00      0.00       1.0
        1030       0.00      0.00      0.00       1.0
        1032       0.00      0.00      0.00       1.0
        1034       0.00      0.00      0.00       1.0
        1037       0.00      0.00      0.00       1.0
        1039       0.00      0.00      0.00       1.0
        1043       0.00      0.00      0.00       1.0
        1046       0.00      0.00      0.00       1.0
        1047       0.00      0.00      0.00       1.0
        1049       0.00      0.00      0.00       1.0
        1052       0.00      0.00      0.00       1.0
        1056       0.00      0.00      0.00       1.0
        1057       0.00      0.00      0.00       1.0
        1060       0.00      0.00      0.00       1.0
        1061       0.00      0.00      0.00       1.0
        1062       0.00      0.00      0.00       1.0
        1066       0.00      0.00      0.00       1.0
        1078       0.00      0.00      0.00       1.0
        1079       0.00      0.00      0.00       1.0
        1089       0.00      0.00      0.00       1.0
        1095       0.00      0.00      0.00       1.0
        1099       0.00      0.00      0.00       1.0
        1108       0.00      0.00      0.00       1.0
        1109       0.00      0.00      0.00       1.0
        1114       0.00      0.00      0.00       1.0
        1121       0.00      0.00      0.00       1.0
        1122       0.00      0.00      0.00       1.0
        1123       0.00      0.00      0.00       1.0
        1125       0.00      0.00      0.00       1.0
        1129       0.00      0.00      0.00       1.0
        1132       0.00      0.00      0.00       1.0
        1134       0.00      0.00      0.00       1.0
        1135       0.00      0.00      0.00       1.0
        1143       0.00      0.00      0.00       0.0
        1152       0.00      0.00      0.00       1.0
        1155       0.00      0.00      0.00       1.0
        1163       0.00      0.00      0.00       1.0
        1164       0.00      0.00      0.00       1.0
        1167       0.00      0.00      0.00       1.0
        1168       0.00      0.00      0.00       1.0
        1169       0.00      0.00      0.00       1.0
        1170       0.00      0.00      0.00       1.0
        1176       0.00      0.00      0.00       1.0
        1179       0.00      0.00      0.00       1.0
        1181       0.00      0.00      0.00       1.0
        1182       0.00      0.00      0.00       0.0
        1187       0.00      0.00      0.00       1.0
        1189       0.00      0.00      0.00       1.0
        1195       0.00      0.00      0.00       1.0
        1198       0.00      0.00      0.00       1.0
        1202       0.00      0.00      0.00       1.0
        1210       0.00      0.00      0.00       1.0
        1213       0.00      0.00      0.00       1.0
        1233       0.00      0.00      0.00       1.0
        1241       0.00      0.00      0.00       1.0
        1243       0.00      0.00      0.00       1.0
        1248       0.00      0.00      0.00       1.0
        1261       0.00      0.00      0.00       1.0
        1263       0.00      0.00      0.00       1.0
        1267       0.00      0.00      0.00       1.0
        1274       0.00      0.00      0.00       1.0
        1276       0.00      0.00      0.00       1.0
        1287       0.00      0.00      0.00       1.0
        1298       0.00      0.00      0.00       1.0
        1299       0.00      0.00      0.00       1.0
        1301       0.00      0.00      0.00       1.0
        1315       0.00      0.00      0.00       1.0
        1319       0.00      0.00      0.00       1.0
        1321       0.00      0.00      0.00       1.0
        1327       0.00      0.00      0.00       1.0
        1328       0.00      0.00      0.00       1.0
        1329       0.00      0.00      0.00       1.0
        1340       0.00      0.00      0.00       1.0
        1344       0.00      0.00      0.00       1.0
        1345       0.00      0.00      0.00       0.0
        1346       0.00      0.00      0.00       1.0
        1350       0.00      0.00      0.00       1.0
        1357       0.00      0.00      0.00       1.0
        1367       0.00      0.00      0.00       1.0
        1368       0.00      0.00      0.00       1.0
        1369       0.00      0.00      0.00       1.0
        1381       0.00      0.00      0.00       1.0
        1385       0.00      0.00      0.00       1.0
        1399       0.00      0.00      0.00       1.0
        1413       0.00      0.00      0.00       1.0
        1414       0.00      0.00      0.00       1.0
        1418       0.00      0.00      0.00       1.0
        1419       0.00      0.00      0.00       1.0
        1420       0.00      0.00      0.00       1.0
        1424       0.00      0.00      0.00       1.0
        1426       0.00      0.00      0.00       1.0
        1427       0.00      0.00      0.00       1.0
        1428       0.00      0.00      0.00       1.0
        1432       0.00      0.00      0.00       1.0
        1436       0.00      0.00      0.00       1.0
        1441       0.00      0.00      0.00       1.0
        1444       0.00      0.00      0.00       1.0
        1472       0.00      0.00      0.00       0.0
        1474       0.00      0.00      0.00       1.0
        1481       0.00      0.00      0.00       1.0
        1486       0.00      0.00      0.00       1.0
        1490       0.00      0.00      0.00       1.0
        1497       0.00      0.00      0.00       1.0
        1498       0.00      0.00      0.00       1.0
        1508       0.00      0.00      0.00       1.0
        1509       0.00      0.00      0.00       1.0
        1510       0.00      0.00      0.00       1.0
        1511       0.00      0.00      0.00       1.0
        1519       0.00      0.00      0.00       1.0
        1520       0.00      0.00      0.00       1.0
        1529       0.00      0.00      0.00       1.0
        1539       0.00      0.00      0.00       1.0
        1541       0.00      0.00      0.00       1.0
        1543       0.00      0.00      0.00       1.0
        1546       0.00      0.00      0.00       1.0
        1552       0.00      0.00      0.00       1.0
        1557       0.00      0.00      0.00       1.0
        1558       0.00      0.00      0.00       1.0
        1565       0.00      0.00      0.00       1.0
        1570       0.00      0.00      0.00       1.0
        1579       0.00      0.00      0.00       1.0
        1585       0.00      0.00      0.00       1.0
        1587       0.00      0.00      0.00       1.0
        1593       0.00      0.00      0.00       1.0
        1595       0.00      0.00      0.00       1.0
        1596       0.00      0.00      0.00       1.0
        1600       0.00      0.00      0.00       1.0
        1605       0.00      0.00      0.00       1.0
        1609       0.00      0.00      0.00       1.0
        1613       0.00      0.00      0.00       1.0
        1617       0.00      0.00      0.00       1.0
        1619       0.00      0.00      0.00       1.0
        1621       0.00      0.00      0.00       1.0
        1623       0.00      0.00      0.00       1.0
        1634       0.00      0.00      0.00       1.0
        1641       0.00      0.00      0.00       1.0
        1650       0.00      0.00      0.00       1.0
        1656       0.00      0.00      0.00       1.0
        1657       0.00      0.00      0.00       1.0
        1659       0.00      0.00      0.00       1.0
        1664       0.00      0.00      0.00       1.0
        1672       0.00      0.00      0.00       1.0
        1673       0.00      0.00      0.00       1.0
        1677       0.00      0.00      0.00       1.0
        1679       0.00      0.00      0.00       1.0
        1682       0.00      0.00      0.00       1.0
        1691       0.00      0.00      0.00       1.0
        1698       0.00      0.00      0.00       1.0
        1701       0.00      0.00      0.00       1.0
        1704       0.00      0.00      0.00       1.0
        1705       0.00      0.00      0.00       1.0
        1710       0.00      0.00      0.00       1.0
        1712       0.00      0.00      0.00       1.0
        1724       0.00      0.00      0.00       1.0
        1725       0.00      0.00      0.00       1.0
        1728       0.00      0.00      0.00       1.0

C:\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
C:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))